Run remote-settings tests in CI
Runs the tests for the remote-settings.py create command in CI.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -85,6 +85,25 @@ jobs:
               echo "Black found code-format changes... Failing CI."
               exit $BLACK_RESULT
             fi
+  test-remote-settings:
+    docker:
+      - image: cimg/python:3.10.2
+    working_directory: ~/mozilla/firefox-translations-models
+    steps:
+      - checkout
+      - run:
+          name: Test remote-settings.py create
+          command: |
+            pip install poetry
+            poetry install
+            poetry run python remote-settings/test-create.py
+            TEST_RESULT=$?
+            if [ $TEST_RESULT -eq 0 ]; then
+              echo "All tests passed... CI passed."
+            else
+              echo "Some tests failed... Failing CI."
+              exit $TEST_RESULT
+            fi
   generate-registry:
     docker:
       - image: cimg/python:3.10.2
@@ -129,6 +148,9 @@ workflows:
   ci:
     jobs:
       - test-python-formatting
+      - test-remote-settings:
+          requires:
+            - test-python-formatting
       - evaluate:
           requires:
             - test-python-formatting
