Remote Settings Script, Initial Entrypoint and Create Subcommand (#113)
* Add Poetry to project

Reworks the project to utilize Poetry. 
This is modeled after the same Poetry setup that exists
in the firefox-translations-training repository.

* Run Black on all Python scripts

Runs the Black formatter on all existing Python code.

* Run black in CI

Runs the black formatter in CI to ensure there are no code format changes.

* Update Poetry dependencies for RemoteSettings script

Updates the Poetry toml and lock files to include all
of the current dependencies for the Remote Settings
script.

* Add main script entry point

Adds the main script entry point using argparse

* Add Error/Help print support

Adds a module to help with printing formatted
error and help messages.

* Add RemoteSettingsClient class implementation

Adds a class implementation for a RemoteSettingsClient
which is currently capable of connecting to the server
and uploading new records with attachments, but is designed
in a way that it will be able to be extended by future subcommands
that will support more CRUD operations.

* Add `create` subcommand

Adds the `create` subcommand to the main CLI interface.
The `create` subcommand is responsible fore creating a new
record with a file attachment on a Remote Settings server.

* Add mocked client and testing

Adds a way to mock the connection to the server for testing.
Adds test cases for error values and happy paths in the `create` command.

* Run remote-settings tests in CI

Runs the tests for the remote-settings.py create command in CI.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -66,6 +66,44 @@ jobs:
             else
               echo "### Nothing to commit"
             fi
+  test-python-formatting:
+    docker:
+      - image: cimg/python:3.10.2
+    working_directory: ~/mozilla/firefox-translations-models
+    steps:
+      - checkout
+      - run:
+          name: Ensure black finds no changes
+          command: |
+            pip install poetry
+            poetry install
+            poetry run black --check .
+            BLACK_RESULT=$?
+            if [ $BLACK_RESULT -eq 0 ]; then
+              echo "Black found no code-format changes... CI passed."
+            else
+              echo "Black found code-format changes... Failing CI."
+              exit $BLACK_RESULT
+            fi
+  test-remote-settings:
+    docker:
+      - image: cimg/python:3.10.2
+    working_directory: ~/mozilla/firefox-translations-models
+    steps:
+      - checkout
+      - run:
+          name: Test remote-settings.py create
+          command: |
+            pip install poetry
+            poetry install
+            poetry run python remote-settings/test-create.py
+            TEST_RESULT=$?
+            if [ $TEST_RESULT -eq 0 ]; then
+              echo "All tests passed... CI passed."
+            else
+              echo "Some tests failed... Failing CI."
+              exit $TEST_RESULT
+            fi
   generate-registry:
     docker:
       - image: cimg/python:3.10.2
@@ -109,7 +147,13 @@ workflows:
   version: 2
   ci:
     jobs:
+      - test-python-formatting
+      - test-remote-settings:
+          requires:
+            - test-python-formatting
       - evaluate:
+          requires:
+            - test-python-formatting
           filters:
             branches:
               # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
