Run black in CI
Runs the black formatter in CI to ensure there are no code format changes.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -66,6 +66,25 @@ jobs:
             else
               echo "### Nothing to commit"
             fi
+  test-python-formatting:
+    docker:
+      - image: cimg/python:3.10.2
+    working_directory: ~/mozilla/firefox-translations-models
+    steps:
+      - checkout
+      - run:
+          name: Ensure black finds no changes
+          command: |
+            pip install poetry
+            poetry install
+            poetry run black --check .
+            BLACK_RESULT=$?
+            if [ $BLACK_RESULT -eq 0 ]; then
+              echo "Black found no code-format changes... CI passed."
+            else
+              echo "Black found code-format changes... Failing CI."
+              exit $BLACK_RESULT
+            fi
   generate-registry:
     docker:
       - image: cimg/python:3.10.2
@@ -109,7 +128,10 @@ workflows:
   version: 2
   ci:
     jobs:
+      - test-python-formatting
       - evaluate:
+          requires:
+            - test-python-formatting
           filters:
             branches:
               # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
